markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Loggator
url: http://blog.loggator.com
description: A fantastic blog that is fantastic.
twitter: loggator
